name: nd-mv-tetsplatting/geo-refine
description: ''
tag: an_astronaut_riding_a_horse
seed: 0
use_timestamp: false
timestamp: ''
exp_root_dir: ./test_on_simple_prompt/tmp
exp_dir: ./test_on_simple_prompt/tmp/nd-mv-tetsplatting/geo-refine
trial_name: an_astronaut_riding_a_horse
trial_dir: ./test_on_simple_prompt/tmp/nd-mv-tetsplatting/geo-refine/an_astronaut_riding_a_horse
n_gpus: 1
resume: null
data_type: Dream3D-Orthogonal
data:
  batch_size: 4
  width: 512
  height: 512
  camera_distance_range:
  - 0.8
  - 0.9
  fovy_range:
  - 40
  - 45
  camera_perturb: 0.0
  center_perturb: 0.0
  up_perturb: 0.0
  elevation_range:
  - 5
  - 30
  azimuth_range:
  - -180
  - 180
  batch_uniform_azimuth: true
  eval_camera_distance: 2.5
  eval_fovy_deg: 40.0
  train_max_step: 2000
  train_val_check: 100
  seed: 0
  multiview_eval: true
  camera_sampling_stone: []
  cond_view: []
  relative: true
system_type: nd-tetsplatting-mv-system
system:
  step_start: 1000
  latent_steps: 0
  geometry_type: implicit-sdf-tetsplatting
  geometry_convert_from: ./test_on_simple_prompt/tmp/nd-mv-tetsplatting/geo/an_astronaut_riding_a_horse/ckpts/last.ckpt
  geometry_convert_inherit_texture: false
  is_refine: true
  geometry:
    radius: 1.0
    n_feature_dims: 0
    isosurface_resolution: 256
    isosurface_deformable_grid: true
    isosurface_coarse_to_fine: true
    s_ratio: 5
    s_start: 20
  material_type: no-material
  anneal_normal_stone:
  - 600
  - 1000
  - 1500
  material:
    n_output_dims: 0
  background_type: solid-color-background
  renderer_type: tetsplatting-rasterizer
  renderer:
    camera_space: true
    mv_bg_colors: blue
    sd_bg_colors: white
  prompt_processor_type: stable-diffusion-prompt-processor
  prompt_processor:
    pretrained_model_name_or_path: stabilityai/stable-diffusion-2-1-base
    prompt: an astronaut riding a horse
    negative_prompt: low quality
  guidance_type: stable-diffusion-dreamtimes-guidance
  guidance:
    pretrained_model_name_or_path: stabilityai/stable-diffusion-2-1-base
    min_step_percent: 0.02
    max_step_percent: 0.5
    guidance_scale: 50.0
    weighting_strategy: fantasia3d
  nd_prompt_processor_type: stable-diffusion-prompt-processor
  nd_prompt_processor:
    pretrained_model_name_or_path: stable-diffusion-v1-5/stable-diffusion-v1-5
    prompt: an astronaut riding a horse
    negative_prompt: low quality
    front_threshold: 30.0
    back_threshold: 30.0
  nd_guidance_type: nd-mv-dmtet-guidance
  nd_guidance:
    model_name: nd-mv
    ckpt_path: pretrained_models/Damo_XR_Lab/Normal-Depth-Diffusion-Model/nd_mv_ema.ckpt
    guidance_scale: 50
    min_step_percent: 0.02
    max_step_percent: 0.5
    recon_loss: true
    recon_std_rescale: 0.5
  loggers:
    wandb:
      enable: false
      project: threestudio
      name: None
  loss:
    lambda_sds: 1.0
    lambda_normal_consistency: 1000.0
    lambda_laplacian_smoothness: 0.0
    sd_loss: 1.0
    nd_sd_loss: 1.0
    eikonal_loss: 1000.0
  optimizer:
    name: AdamW
    args:
      lr: 0.001
      betas:
      - 0.9
      - 0.99
      eps: 1.0e-15
trainer:
  max_steps: 2000
  log_every_n_steps: 100
  num_sanity_val_steps: 1
  val_check_interval: 100
  enable_progress_bar: true
  precision: 16-mixed
checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: 2000
